spring.application.name=resume-matcher
#server.port=8080
ollama.url=http://localhost:11434
# Use this exact name
ollama.model=llama3.2

## Database configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/resume_matcher
#spring.datasource.username=postgres
#spring.datasource.password=Abhi@98852
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# File upload settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# allow your React dev server
spring.mvc.cors.allowed-origins=http://localhost:3000
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.mvc.cors.allowed-headers=*